### ISSUE TITLE
Errors and warnings

### ISSUE THREAD

**Issue by julesjacobsen** [yaseminbridges/phenotype2phenopacket#1]
```
p2p create --phenotype-annotation phenotype.hpoa --output-dir phenopackets-out
/usr/lib/python3/dist-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
/home/jules/.local/lib/python3.10/site-packages/pronto/ontology.py:206: UnicodeWarning: unsound encoding, assuming ISO-8859-1 (73% confidence)
  return cls(
Traceback (most recent call last):
  File "/home/jules/.local/bin/p2p", line 8, in <module>
    sys.exit(main())
  File "/home/jules/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jules/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jules/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jules/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jules/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/cli_create.py", line 40, in create_synthetic_patient_command
    create_synthetic_patients(phenotype_annotation_df, num_disease, output_dir)
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/create/create.py", line 43, in create_synthetic_patients
    create_synthetic_patient_phenopacket(
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/create/create.py", line 21, in create_synthetic_patient_phenopacket
    patient_terms = synthetic_patient_generator.patient_term_annotation_set()
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/utils/phenopacket_utils.py", line 295, in patient_term_annotation_set
    patient_terms = self.get_patient_terms()
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/utils/phenopacket_utils.py", line 217, in get_patient_terms
    return self.filter_phenotype_entries(
  File "/home/jules/.local/lib/python3.10/site-packages/phenotype2phenopacket/utils/phenopacket_utils.py", line 213, in filter_phenotype_entries
    return pl.from_dicts(self.filtered_df)
  File "/home/jules/.local/lib/python3.10/site-packages/polars/convert.py", line 177, in from_dicts
    raise NoDataError("No rows. Cannot infer schema.")
exceptions.NoDataError: No rows. Cannot infer schema.
```

**Comment by yaseminbridges** [comment]
I think this is an issue where 0 patient terms were selected to be the proportion of terms to be selected from the fullest. This should be hopefully be fixed now
